<a href="https://colab.research.google.com/github/victormaciase/Energy/blob/main/CapacidadGeneracion.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
import pandas as pd

In [16]:
# URL raw del archivo Excel en GitHub
url_data = "https://raw.githubusercontent.com/victormaciase/Energy/main/datos/se_capacidad_instalada_gx.csv"

df = pd.read_csv(url_data, sep=';')

## **Pregunta 1**

¿Cuántas observaciones y variables contiene el dataset?

In [17]:
df.shape  # número de observaciones y variables

(1342, 42)

## **Pregunta 2**

¿Cuántas observaciones hay por sistema?

In [18]:
df['sistema'].value_counts()

sistema
SEN               1206
SEA                 63
SEM                 54
LOS LAGOS           12
ISLA DE PASCUA       7
Name: count, dtype: int64

## **Pregunta 3**

¿Cuántas centrales están en estado de prueba? ¿Dónde se encuentran? ¿Que fuente de energía tienen?

In [19]:
df['estado'].value_counts()

estado
En Operacion    1340
En Pruebas         2
Name: count, dtype: int64

Las centrales a prueba son:

In [20]:
df[df['estado'] == "En Pruebas"][['sistema','region_nombre', 'tipo_de_energia', 'potencia_bruta_mw', 'potencia_neta_mw']]

,sistema,region_nombre,tipo_de_energia,potencia_bruta_mw,potencia_neta_mw
626,SEN,Región Metropolitana de Santiago,Solar,"9,0045",9
1323,SEN,Región de Coquimbo,Petróleo Diesel,0,0

## **Pregunta 4**

¿Cuál es la potencia bruta y neta de los sistemas Los Lagos e Isla de Pascua?

In [9]:
df[(df['estado'] == "En Operacion") &
  (df['sistema'].isin(['LOS LAGOS', 'ISLA DE PASCUA']))][['sistema', 'subsistema', 'tipo_de_energia','potencia_bruta_mw', 'potencia_neta_mw']]

,sistema,subsistema,tipo_de_energia,potencia_bruta_mw,potencia_neta_mw
10,LOS LAGOS,COCHAMO,Hidráulica Pasada,"0,8","0,78"
11,LOS LAGOS,COCHAMO,Hidráulica Pasada,"0,68","0,68"
23,LOS LAGOS,COCHAMO,Petróleo Diesel,"0,8","0,8"
24,LOS LAGOS,COCHAMO,Petróleo Diesel,1,1
25,LOS LAGOS,COCHAMO,Petróleo Diesel,1,1
27,LOS LAGOS,HORNOPIREN,Hidráulica Pasada,"0,765","0,765"
51,LOS LAGOS,HORNOPIREN,Petróleo Diesel,"0,75","0,75"
52,LOS LAGOS,HORNOPIREN,Petróleo Diesel,"0,75","0,75"
53,LOS LAGOS,HORNOPIREN,Petróleo Diesel,"0,75","0,75"
54,LOS LAGOS,HORNOPIREN,Petróleo Diesel,"0,8","0,82"
145,LOS LAGOS,COCHAMO,Petróleo Diesel,"0,8","0,8"
146,LOS LAGOS,COCHAMO,Petróleo Diesel,"0,8","0,8"
147,ISLA DE PASCUA,ISLA DE PASCUA,Solar Fotovoltaica,"0,1","0,1"
148,ISLA DE PASCUA,ISLA DE PASCUA,Petróleo Diesel,"1,36","1,09"
149,ISLA DE PASCUA,ISLA DE PASCUA,Petróleo Diesel,"0,8","0,64"
150,ISLA DE PASCUA,ISLA DE PASCUA,Petróleo Diesel,"0,8","0,64"
151,ISLA DE PASCUA,ISLA DE PASCUA,Petróleo Diesel,"0,8","0,64"
152,ISLA DE PASCUA,ISLA DE PASCUA,Petróleo Diesel,"0,8","0,64"
153,ISLA DE PASCUA,ISLA DE PASCUA,Petróleo Diesel,"0,8","0,64"

In [11]:
df['potencia_neta_mw'] = df['potencia_neta_mw'].str.replace(',', '.', regex=False).astype(float)
df[(df['estado'] == "En Operacion") &
  (df['sistema'].isin(['LOS LAGOS', 'ISLA DE PASCUA']))]['potencia_neta_mw'].sum()

np.float64(14.085000000000003)

## **Pregunta 5**

¿Cuál es la potencia bruta y neta de la Central localizada en Salta (Argentina)?

In [22]:
df[df['region_nombre'] == "Salta (Argentina)"][['sistema','subsistema', 'propietario','tipo_de_energia','potencia_bruta_mw', 'potencia_neta_mw']]

,sistema,subsistema,propietario,tipo_de_energia,potencia_bruta_mw,potencia_neta_mw
1209,SEN,SING,AES GENER,Gas Natural,380,380

In [23]:
df.head()

,sistema,subsistema,propietario,razon_social,rut,central,estado,fecha_puesta_servicio_central,anio_servicio_central,region_nombre,...,unidad_3,tipo_turbina_hidraulica,gasto_m3_por_s,caida_m,coord_este_utm,coord_norte_utm,huso_utm,tipo_final,orden,fecha_act
0,SEA,AYSEN,EDELAYSEN,Empresa Eléctrica de Aisén S.A.,88.272.600-2,ALTO BAGUALES 2,En Operacion,01/01/2016,2016.0,Región Aisén del Gral.Carlos Ibáñez del Campo,...,NaN,NaN,NaN,NaN,"726258,7977","5045322,821",18S,Eólica,15.0,10/08/2026
1,SEA,AYSEN,EDELAYSEN,Empresa Eléctrica de Aisén S.A.,88.272.600-2,ALTO BAGUALES 2,En Operacion,01/01/2016,2016.0,Región Aisén del Gral.Carlos Ibáñez del Campo,...,NaN,NaN,NaN,NaN,"726258,7977","5045322,821",18S,Eólica,15.0,10/08/2026
2,SEA,AYSEN,EDELAYSEN,Empresa Eléctrica de Aisén S.A.,88.272.600-2,AYSEN TÉRMICO,En Operacion,01/01/1997,1997.0,Región Aisén del Gral.Carlos Ibáñez del Campo,...,NaN,NaN,NaN,NaN,"679309,0822","5027217,691",18S,Petróleo Diesel,15.0,10/08/2026
3,SEA,AYSEN,EDELAYSEN,Empresa Eléctrica de Aisén S.A.,88.272.600-2,AYSEN TÉRMICO,En Operacion,01/01/1997,1997.0,Región Aisén del Gral.Carlos Ibáñez del Campo,...,NaN,NaN,NaN,NaN,"679309,0822","5027217,691",18S,Petróleo Diesel,15.0,10/08/2026
4,SEA,AYSEN,EDELAYSEN,Empresa Eléctrica de Aisén S.A.,88.272.600-2,AYSEN,En Operacion,01/01/1960,1960.0,Región Aisén del Gral.Carlos Ibáñez del Campo,...,NaN,Francis,"3,3",103,"679309,0822","5027217,691",18S,Mini Hidráulica de Pasada,15.0,10/08/2026

Filtrando solo plantas en operación, se tiene:

In [ ]:
df1 = df[(df['estado'] == "En Operacion") &
 (df['region_nombre'] != "Salta (Argentina)") &
  (df['sistema'].isin(['SEN', 'SEA', 'SEM']))]
df1.head()

,sistema,subsistema,propietario,razon_social,rut,central,estado,fecha_puesta_servicio_central,anio_servicio_central,region_nombre,...,unidad_3,tipo_turbina_hidraulica,gasto_m3_por_s,caida_m,coord_este_utm,coord_norte_utm,huso_utm,tipo_final,orden,fecha_act
0,SEA,AYSEN,EDELAYSEN,Empresa Eléctrica de Aisén S.A.,88.272.600-2,ALTO BAGUALES 2,En Operacion,01/01/2016,2016.0,Región Aisén del Gral.Carlos Ibáñez del Campo,...,NaN,NaN,NaN,NaN,"726258,7977","5045322,821",18S,Eólica,15.0,10/08/2026
1,SEA,AYSEN,EDELAYSEN,Empresa Eléctrica de Aisén S.A.,88.272.600-2,ALTO BAGUALES 2,En Operacion,01/01/2016,2016.0,Región Aisén del Gral.Carlos Ibáñez del Campo,...,NaN,NaN,NaN,NaN,"726258,7977","5045322,821",18S,Eólica,15.0,10/08/2026
2,SEA,AYSEN,EDELAYSEN,Empresa Eléctrica de Aisén S.A.,88.272.600-2,AYSEN TÉRMICO,En Operacion,01/01/1997,1997.0,Región Aisén del Gral.Carlos Ibáñez del Campo,...,NaN,NaN,NaN,NaN,"679309,0822","5027217,691",18S,Petróleo Diesel,15.0,10/08/2026
3,SEA,AYSEN,EDELAYSEN,Empresa Eléctrica de Aisén S.A.,88.272.600-2,AYSEN TÉRMICO,En Operacion,01/01/1997,1997.0,Región Aisén del Gral.Carlos Ibáñez del Campo,...,NaN,NaN,NaN,NaN,"679309,0822","5027217,691",18S,Petróleo Diesel,15.0,10/08/2026
4,SEA,AYSEN,EDELAYSEN,Empresa Eléctrica de Aisén S.A.,88.272.600-2,AYSEN,En Operacion,01/01/1960,1960.0,Región Aisén del Gral.Carlos Ibáñez del Campo,...,NaN,Francis,"3,3",103,"679309,0822","5027217,691",18S,Mini Hidráulica de Pasada,15.0,10/08/2026

El número de observaciones por sistema es:

In [ ]:
df1['sistema'].value_counts()

sistema
SEN    1203
SEA      63
SEM      54
Name: count, dtype: int64

In [ ]:
#df1['potencia_bruta_mw'] = df1['potencia_bruta_mw'].str.replace(',', '.', regex=False).astype(float)
df1.groupby('region_nombre')[['potencia_bruta_mw', 'potencia_neta_mw']].sum()

,potencia_bruta_mw,potencia_neta_mw
region_nombre,,
Región Aisén del Gral.Carlos Ibáñez del Campo,67.570000,67.484000
Región Metropolitana de Santiago,2453.168516,2402.430915
Región de Antofagasta,11465.577600,11069.848200
Región de Arica y Parinacota,167.778200,166.719800
Región de Atacama,5574.985700,5424.926000
Región de Coquimbo,2118.369180,2086.435080
Región de La Araucanía,1126.205500,1100.293700
Región de Los Lagos,971.347150,961.094810
Región de Los Ríos,359.759950,357.224600
Región de Magallanes y de la Antártica Chilena,142.978000,128.680200
Región de Tarapacá,673.806900,654.871665
Región de Valparaíso,3537.485422,3441.017550
Región de Ñuble,412.317670,404.979450
Región del Biobío,5438.878220,5186.816700
Región del Libertador Gral. Bernardo O’Higgins,2176.382940,2136.927530
Región del Maule,2897.491699,2848.545880

In [ ]:
print(df1.columns)

Index(['sistema', 'subsistema', 'propietario', 'razon_social', 'rut',
       'central', 'estado', 'fecha_puesta_servicio_central',
       'anio_servicio_central', 'region_nombre', 'comuna_nombre', 'cod_unidad',
       'tipo_unidad', 'fecha_servicio_unidad', 'unidades', 'marca_modelo',
       'clasificacion', 'tipo_de_energia', 'potencia_bruta_mw',
       'potencia_neta_mw', 'ley_ernc', 'medio_generacion', 'distribuidora',
       'punto_conexion', 'combustible_1', 'consumo_1', 'unidad_1',
       'combustible_2', 'consumo_2', 'unidad_2', 'combustible_3', 'consumo_3',
       'unidad_3', 'tipo_turbina_hidraulica', 'gasto_m3_por_s', 'caida_m',
       'coord_este_utm', 'coord_norte_utm', 'huso_utm', 'tipo_final', 'orden',
       'fecha_act'],
      dtype='object')

In [ ]:
df1.groupby('tipo_de_energia')['potencia_neta_mw'].sum()

tipo_de_energia
Biogas                       58.457100
Biomasa                     519.690500
Biomasa-Petróleo N°6         88.000000
Carbón                     2809.688000
Carbón - Petcoke            702.659000
Cogeneración                 20.068200
Eólica                     6310.425300
Fuel Oil Nro. 6              35.435465
Gas Natural                3863.729300
Geotérmica                   83.580000
Hidráulica Embalse         3503.572600
Hidráulica Pasada          3432.044550
Mini Hidráulica Pasada      576.055375
Petcoke                      20.500000
Petróleo Diesel            3850.469530
Propano                      14.610000
Solar                     12438.081160
Solar Fotovoltaica            2.960000
Solar-CSP                   108.270000
Name: potencia_neta_mw, dtype: float64

In [ ]:
df1['tipo_de_energia2'] = df1['tipo_de_energia'].replace({
    'Solar Fotovoltaica': 'Solar',
    'Solar-CSP': 'Solar',
    'Carbón - Petcoke': 'Carbón',
    'Petcoke': 'Carbón',
    'Mini Hidráulica Pasada': 'Hidráulica',
    'Hidráulica Pasada': 'Hidráulica',
    'Hidráulica Embalse': 'Hidráulica',
    'Cogeneración': 'Gas Natural',
    'Propano': 'Gas Natural',
    'Biogas': 'Biomasa',
    'Biomasa-Petróleo N°6': 'Biomasa',
    'Fuel Oil Nro. 6': 'Petróleo Diesel'

})

print("Nuevas categorías de 'tipo_de_energia' después de agrupar:")
df1['tipo_de_energia2'].value_counts()

Nuevas categorías de 'tipo_de_energia' después de agrupar:

/tmp/ipykernel_663/326730095.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['tipo_de_energia2'] = df1['tipo_de_energia'].replace({

tipo_de_energia2
Solar              759
Petróleo Diesel    204
Hidráulica         194
Eólica              73
Gas Natural         46
Biomasa             32
Carbón              11
Geotérmica           1
Name: count, dtype: int64

In [ ]:
df1.groupby('tipo_de_energia2')['potencia_neta_mw'].sum()

tipo_de_energia2
Biomasa              666.147600
Carbón              3532.847000
Eólica              6310.425300
Gas Natural         3898.407500
Geotérmica            83.580000
Hidráulica          7511.672525
Petróleo Diesel     3885.904995
Solar              12549.311160
Name: potencia_neta_mw, dtype: float64

In [ ]:
df1.groupby('sistema')['potencia_neta_mw'].sum().round(0)

sistema
SEA       74.0
SEM      129.0
SEN    38236.0
Name: potencia_neta_mw, dtype: float64

In [ ]:
df1[df1['sistema'] == "SEA"].groupby('tipo_de_energia2')['potencia_neta_mw'].sum().round(0)

tipo_de_energia2
Eólica              2.0
Hidráulica         25.0
Petróleo Diesel    44.0
Solar               3.0
Name: potencia_neta_mw, dtype: float64

In [ ]:
df1[df1['sistema'] == "SEM"].groupby('tipo_de_energia2')['potencia_neta_mw'].sum().round(0)

tipo_de_energia2
Eólica             12.0
Gas Natural        99.0
Petróleo Diesel    18.0
Name: potencia_neta_mw, dtype: float64

In [ ]:
df1[df1['sistema'] == "SEN"].groupby('tipo_de_energia2')['potencia_neta_mw'].sum().round(0)

tipo_de_energia2
Biomasa              666.0
Carbón              3533.0
Eólica              6297.0
Gas Natural         3799.0
Geotérmica            84.0
Hidráulica          7486.0
Petróleo Diesel     3824.0
Solar              12546.0
Name: potencia_neta_mw, dtype: float64

In [ ]:
import plotly.express as px

df_sen = df1[df1['sistema'] == "SEN"]

# Agrupar por tipo_de_energia y sumar la potencia bruta
df_treemap = df_sen.groupby('tipo_de_energia2')['potencia_neta_mw'].sum().reset_index()

# Crear el treemap
fig = px.treemap(df_treemap, path=[px.Constant("SEN"), 'tipo_de_energia2'],
                 values='potencia_neta_mw',
                 title='Distribución de Potencia Neta (MW) por Tipo de Energía en la Región de Los Lagos')

fig.update_layout(margin = dict(t=50, l=25, r=25, b=25))
fig.show()